# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6747f9960cab6ce6704f2d5133c4a5d71c9dff18f622119ac53f225d6b2f7e2d56aaf2b8397dff4b91037b336f36fec61ae67b12f9ac58d6c5453a45541100e1

test:
  secret_key_base: 71c7b8723ee1010492756d572b61272cf5cfffc14cbc4b4c515e9b9cbd273dba080b1fd7880ff9d4420442f70309404f22ff4d97d2e5b26e36723bcf0c29e9ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
